# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-25 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GOD', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bindhosts',
            options={'verbose_name': '主机和用户表', 'verbose_name_plural': '主机和用户表'},
        ),
        migrations.AlterModelOptions(
            name='host',
            options={'verbose_name': '主机表', 'verbose_name_plural': '主机表'},
        ),
        migrations.AlterModelOptions(
            name='hostgroups',
            options={'verbose_name': '主机组表', 'verbose_name_plural': '主机组表'},
        ),
        migrations.AlterModelOptions(
            name='hostuser',
            options={'verbose_name': '主机账户表', 'verbose_name_plural': '主机账户表'},
        ),
        migrations.AlterModelOptions(
            name='idc',
            options={'verbose_name': '机房表', 'verbose_name_plural': '机房表'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': '用户表', 'verbose_name_plural': '用户表'},
        ),
        migrations.AlterField(
            model_name='hostuser',
            name='username',
            field=models.CharField(max_length=64, verbose_name='主机用户名'),
        ),
    ]
