# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-28 14:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GOD', '0002_auto_20171225_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='idc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='GOD.IDC'),
        ),
    ]
