# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-28 14:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GOD', '0003_auto_20171228_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bindhosts',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='GOD.Host'),
        ),
        migrations.AlterField(
            model_name='bindhosts',
            name='host_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='GOD.HostUser'),
        ),
    ]
