# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-01-07 13:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GOD', '0004_auto_20171228_2255'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('logtime', models.DateTimeField(auto_now_add=True)),
                ('bindhost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GOD.BindHosts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
