# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-01-17 13:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GOD', '0005_userlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taskdetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveIntegerField(choices=[(0, 'failed'), ('1', 'sucess')])),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('event_log', models.TextField()),
                ('bind_host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GOD.BindHosts')),
            ],
            options={
                'verbose_name': '任务详细',
                'verbose_name_plural': '任务详细',
            },
        ),
        migrations.CreateModel(
            name='TaskLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=128)),
                ('cmd_str', models.CharField(max_length=1024)),
                ('task_id', models.PositiveIntegerField()),
                ('task_time', models.DateTimeField(auto_now_add=True)),
                ('task_type', models.CharField(choices=[('cmd', 'CMD'), ('file_send', '批量发送文件'), ('file_get', '批量下载文件')], max_length=50)),
                ('selected_host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GOD.BindHosts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '任务日志',
                'verbose_name_plural': '任务日志',
            },
        ),
        migrations.AddField(
            model_name='taskdetail',
            name='children_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GOD.TaskLog'),
        ),
    ]
