# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-01-17 14:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GOD', '0006_auto_20180117_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklog',
            name='selected_host',
        ),
    ]
