# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-01-17 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GOD', '0007_remove_tasklog_selected_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklog',
            name='tag_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
