# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-01-17 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GOD', '0008_auto_20180117_2304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklog',
            name='task_id',
        ),
        migrations.AddField(
            model_name='tasklog',
            name='task_pid',
            field=models.IntegerField(default=0),
        ),
    ]
