# Generated by Django 2.0 on 2018-01-18 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GOD', '0009_auto_20180117_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdetail',
            name='bind_host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='GOD.BindHosts'),
        ),
        migrations.AlterField(
            model_name='taskdetail',
            name='children_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='GOD.TaskLog'),
        ),
        migrations.AlterField(
            model_name='tasklog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='bindhost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='GOD.BindHosts'),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
