# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-01-18 16:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GOD', '0013_tasklog_hosts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklog',
            name='hosts',
        ),
    ]
