# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-01-21 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GOD', '0015_auto_20180118_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskdetail',
            name='status',
        ),
        migrations.AddField(
            model_name='taskdetail',
            name='result',
            field=models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('unknown', 'Unknown')], default='unknown', max_length=30),
        ),
    ]
