# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-01-21 04:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GOD', '0016_auto_20180121_0303'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklog',
            name='host_list',
            field=models.ManyToManyField(to='GOD.BindHosts'),
        ),
    ]
