# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-01-26 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GOD', '0021_auto_20180124_0026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emailcontent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('from_addr', models.EmailField(max_length=254)),
                ('to_addr', models.EmailField(max_length=254)),
                ('content', models.CharField(max_length=1024)),
                ('cc_addr', models.EmailField(max_length=254)),
            ],
        ),
    ]
