# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-01-26 17:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GOD', '0022_emailcontent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailcontent',
            options={'verbose_name': '邮件', 'verbose_name_plural': '邮件'},
        ),
    ]
