# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-01-30 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GOD', '0023_auto_20180127_0114'),
    ]

    operations = [
        migrations.CreateModel(
            name='GITTASK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('git_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='SCPTASK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scp_type', models.PositiveSmallIntegerField(choices=[(0, 'get'), (1, 'put')])),
                ('local_path', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='SSHTASK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exec_cmd', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='TaskJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TaskPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='TaskStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('taskplan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GOD.TaskPlan')),
            ],
        ),
        migrations.AddField(
            model_name='taskjob',
            name='taskstage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GOD.TaskStage'),
        ),
        migrations.AddField(
            model_name='sshtask',
            name='tasktype',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='GOD.TaskJob'),
        ),
        migrations.AddField(
            model_name='scptask',
            name='tasktype',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='GOD.TaskJob'),
        ),
    ]
