# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-01-31 02:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GOD', '0025_taskjob_task_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scptask',
            old_name='tasktype',
            new_name='taskjob',
        ),
        migrations.RenameField(
            model_name='sshtask',
            old_name='tasktype',
            new_name='taskjob',
        ),
    ]
