# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-01-31 06:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GOD', '0026_auto_20180131_1039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gittask',
            options={'verbose_name': 'GIT插件', 'verbose_name_plural': 'GIT插件'},
        ),
        migrations.AlterModelOptions(
            name='scptask',
            options={'verbose_name': 'SCP插件', 'verbose_name_plural': 'SCP插件'},
        ),
        migrations.AlterModelOptions(
            name='sshtask',
            options={'verbose_name': 'SSH插件', 'verbose_name_plural': 'SSH插件'},
        ),
    ]
