# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-02-01 13:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GOD', '0027_auto_20180131_1446'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sshtask',
            options={'verbose_name': 'SSH插件s', 'verbose_name_plural': 'SSH插件s'},
        ),
    ]
