# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-02-01 14:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GOD', '0028_auto_20180201_2151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sshtask',
            options={'verbose_name': 'SSH插件', 'verbose_name_plural': 'SSH插件'},
        ),
        migrations.AddField(
            model_name='scptask',
            name='bindhost',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='GOD.BindHosts'),
        ),
        migrations.AddField(
            model_name='sshtask',
            name='bindhost',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='GOD.BindHosts'),
        ),
    ]
