# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-02-01 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GOD', '0029_auto_20180201_2229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sshtask',
            name='bindhost',
        ),
        migrations.AddField(
            model_name='sshtask',
            name='bindhost',
            field=models.ManyToManyField(default=0, to='GOD.BindHosts'),
        ),
    ]
