# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-02-01 14:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GOD', '0030_auto_20180201_2231'),
    ]

    operations = [
        migrations.CreateModel(
            name='PIPtask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('args', models.TextField(default='')),
                ('taskjob', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='GOD.TaskJob')),
            ],
        ),
        migrations.AddField(
            model_name='gittask',
            name='taskjob',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='GOD.TaskJob'),
        ),
    ]
