# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-04 15:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GOD', '0032_auto_20180204_1525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskplan',
            old_name='planame',
            new_name='planname',
        ),
    ]
