# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-05 04:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GOD', '0033_auto_20180204_1529'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sshtask',
            old_name='bindhost',
            new_name='bindhosts',
        ),
        migrations.AddField(
            model_name='scptask',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='sshtask',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
