# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-05 04:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GOD', '0034_auto_20180205_0419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scptask',
            name='bindhost',
        ),
        migrations.AddField(
            model_name='scptask',
            name='bindhost',
            field=models.ManyToManyField(default=0, to='GOD.BindHosts'),
        ),
    ]
