# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-07 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GOD', '0035_auto_20180205_0423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sshtask',
            name='bindhosts',
            field=models.ManyToManyField(to='GOD.BindHosts'),
        ),
    ]
