# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-07 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GOD', '0036_auto_20180207_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scptask',
            name='bindhost',
            field=models.ManyToManyField(to='GOD.BindHosts'),
        ),
    ]
