# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-07 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GOD', '0037_auto_20180207_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='gittask',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='piptask',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
