# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-18 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GOD', '0038_auto_20180207_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='gittask',
            name='bindhost',
            field=models.ManyToManyField(to='GOD.BindHosts'),
        ),
        migrations.AddField(
            model_name='piptask',
            name='bindhost',
            field=models.ManyToManyField(to='GOD.BindHosts'),
        ),
    ]
